name: Oliveyoung Ranking Scraper

on:
  schedule:
    - cron: "0 0 * * *"  # 매일 00:00 UTC (한국시간 09:00)
  workflow_dispatch: # 수동 실행 가능

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run scraper
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: python main.py
