jobs:
  run:
    runs-on: ubuntu-latest

    # ✅ 모든 스텝이 상속받게 job 레벨에 시크릿 주입
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DROPBOX_APP_KEY: ${{ mt8yis35ti7nvd4 }}
      DROPBOX_APP_SECRET: ${{ 4plpjwlnhvg0ywl }}
      DROPBOX_REFRESH_TOKEN: ${{ xr1apKHpE1sAAAAAAAAAAQ12r0xlvuSSSsFZGg9s8kzJMX5n0Xaq-np7R6oOw_AH }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3 playwright
          python -m playwright install chromium

      # ✅ 시크릿 주입 여부를 바로 로그로 확인
      - name: Debug env presence
        run: |
          python - << 'PY'
          import os
          for k in ["SLACK_WEBHOOK_URL","DROPBOX_APP_KEY","DROPBOX_APP_SECRET","DROPBOX_REFRESH_TOKEN"]:
              print(k, "=", "SET" if os.getenv(k) else "MISSING")
          PY

      - name: Run app
        run: python app.py
