# .github/workflows/run.yml
name: OliveYoung Ranking

on:
  schedule:
    - cron: "1 5 * * *"   # KST 14:01
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    # ✅ JOB 레벨에 시크릿 주입(모든 스텝 상속)
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3 playwright
          python -m playwright install chromium

      # 🔎 디버그: 값 존재 여부만(실제 값은 안 찍음)
      - name: Debug env presence
        run: |
          python - << 'PY'
          import os
          def ok(k): print(f"{k} set =", "YES" if os.getenv(k) else "NO")
          for k in ["SLACK_WEBHOOK_URL","DROPBOX_APP_KEY","DROPBOX_APP_SECRET","DROPBOX_REFRESH_TOKEN"]:
              ok(k)
          PY

      - name: Run app
        run: python app.py

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: oy-debug
          path: |
            rankings/**
            artifacts/**
          if-no-files-found: ignore
