# .github/workflows/run.yml (핵심만)
jobs:
  run:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      GDRIVE_SA_JSON_B64: ${{ secrets.GDRIVE_SA_JSON_B64 }}
      GDRIVE_FOLDER_ID:   ${{ secrets.GDRIVE_FOLDER_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3 playwright google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib
          python -m playwright install chromium
      - name: Run app
        run: python app.py
