jobs:
  run:
    runs-on: ubuntu-latest

    env:   # ✅ 여기!
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.10" }
      - run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3 playwright
          python -m playwright install chromium
      - name: Debug env presence
        run: |
          python - << 'PY'
          import os
          for k in ["SLACK_WEBHOOK_URL","DROPBOX_APP_KEY","DROPBOX_APP_SECRET","DROPBOX_REFRESH_TOKEN"]:
              print(k, "=", "SET" if os.getenv(k) else "MISSING")
          PY
      - run: python app.py
